// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrcaFacil.Core.Data;

#nullable disable

namespace OrcaFacil.Core.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903154000_AddMetaReducaoToOrcamento")]
    partial class AddMetaReducaoToOrcamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("OrcaFacil.Core.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorHex")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EhPadraoDoSistema")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("TipoPadrao")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("OrcaFacil.Core.Entities.MembroFamilia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MembrosFamilia");
                });

            modelBuilder.Entity("OrcaFacil.Core.Entities.Meta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Concluida")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<int>("MembroFamiliaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Prazo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorAlvo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorAtual")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MembroFamiliaId");

                    b.ToTable("Metas");
                });

            modelBuilder.Entity("OrcaFacil.Core.Entities.Orcamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MetaReducaoPercentual")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mes")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorLimite")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId", "Mes", "Ano")
                        .IsUnique();

                    b.ToTable("Orcamentos");
                });

            modelBuilder.Entity("OrcaFacil.Core.Entities.Transacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("MembroFamiliaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Pago")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Recorrencia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TransacaoOrigemId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("MembroFamiliaId");

                    b.HasIndex("TransacaoOrigemId");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("OrcaFacil.Core.Entities.Meta", b =>
                {
                    b.HasOne("OrcaFacil.Core.Entities.MembroFamilia", "MembroFamilia")
                        .WithMany("Metas")
                        .HasForeignKey("MembroFamiliaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MembroFamilia");
                });

            modelBuilder.Entity("OrcaFacil.Core.Entities.Orcamento", b =>
                {
                    b.HasOne("OrcaFacil.Core.Entities.Categoria", "Categoria")
                        .WithMany("Orcamentos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("OrcaFacil.Core.Entities.Transacao", b =>
                {
                    b.HasOne("OrcaFacil.Core.Entities.Categoria", "Categoria")
                        .WithMany("Transacoes")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrcaFacil.Core.Entities.MembroFamilia", "MembroFamilia")
                        .WithMany("Transacoes")
                        .HasForeignKey("MembroFamiliaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrcaFacil.Core.Entities.Transacao", "TransacaoOrigem")
                        .WithMany()
                        .HasForeignKey("TransacaoOrigemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");

                    b.Navigation("MembroFamilia");

                    b.Navigation("TransacaoOrigem");
                });

            modelBuilder.Entity("OrcaFacil.Core.Entities.Categoria", b =>
                {
                    b.Navigation("Orcamentos");

                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("OrcaFacil.Core.Entities.MembroFamilia", b =>
                {
                    b.Navigation("Metas");

                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
